import Footer from "@/components/Footer";
import { NavBar } from "@/components/NavBar";
import { theme } from "@/components/theme";
import { ThemeProvider } from "@mui/material";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          backgroundColor: "#222831",
        }}
      >
        <ThemeProvider theme={theme}>
          <header>
            <NavBar />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
